@startuml

class Article {
- name: String
- author: String
- id: int
- releaseDate: LocalDate

+ Article()
+ Article(String name, String author, int id, LocalDate releaseDate)
+ getName(): String
+ setName(String name): void
+ getAuthor(): String
+ setAuthor(String author): void
+ getId: int
+ setId(int id): void
+ getReleaseDate(): LocalDate
+ setReleaseDate(LocalDate releaseDate): void
+ toString(): String
}

@enduml