@startuml

class ClientService {
-ClientRepository clientRepository;
+ClientService(ClientRepository);

+addClient(Client client)
+removeClient(int id)
+findClient(String name) : Client
+findClient(int id) : Client
+sortClient(SortType sortType)

}

@enduml