@startuml

class Client {
- name: String
- Id: int

+ Client()
+ Client(String name, int id)
+ getName(): String
+ setName(String name): void
+ getId(): int
+ setId(int id): void
+ toString(): String
}

@enduml