@startuml

User -> AnimalShelterApp : provides an animal
AnimalShelterApp -> AnimalService : addAnimal(Animal animal)

alt Animal not in the shelter
AnimalService -> AnimalService : set ID to animal
AnimalService -> AnimalService : add animal in the shelter
AnimalService -> AnimalShelterApp : return true
User <-- AnimalShelterApp : success msg: animal added

else Animal already in the shelter
AnimalService -> AnimalShelterApp : return false
User <-- AnimalShelterApp : error msg: animal already exists

end

@enduml
