@startuml

start
:employee asks to see all articles in the library;
:system search all articles in the library;
if(are there any articles found) then (yes)
    :system show result;
    end;
else (no)
    :error msg there are no articles in the library;
    stop;

@enduml