@startuml

start
:employee asks to see all clients in the library;
:system search all clients in the library;
if(are there any clients found) then (yes)
    :system show result;
    end;
else (no)
    :error msg there are no clients in the library;
    stop;
@enduml