@startuml

start
:employee  article;
if (article is in library) then (yes)
    :provide article;
    end;
else (no)
    :article is not in library;
    :error message "Article not found";
    end

@enduml