@startuml
start
:employee provides sorting method by name or Id;

if(sorting by name) then (yes)
    :system retrieves the articles;
    :system sort the articles by name;
    end;
else (no, sort by Id)
        :system retrieves the articles;
        :system sort the articles by Id;
        end;
@enduml