@startuml
start
:employee provides article;
if(article already in library) then (yes)
    :increment stock of the article;
    end;
else (no)
    :set ID to article;
    :add article to stock;
    end;
@enduml