
@startuml
start
:client provides article;
:employee checks article condition;
if(article has damage) then (yes)
:error message, pay fine;
end;
else(no)
:employee update article stock;
:decrease client stock;
end;

@enduml
