@startuml
left to right direction

rectangle Articles {
(find article) as findArticle
(borrow article) as borrowArticle
(return article) as returnArticle
(add article) as addArticle
(remove article) as removeArticle
(sort articles) as sortArticle
(return all articles) as returnAllArticle
}

rectangle Clients {
(add client) as addClient
(remove client) as removeClient
(find client) as findClient
(return all clients) as returnAllClients
}

client --> borrowArticle
client --> returnArticle

employee --> addClient
employee --> removeClient
employee --> findClient

employee --> addArticle
employee --> removeArticle
employee --> findArticle
employee --> sortArticle
employee --> returnAllArticle
employee --> returnAllClients

@enduml