@startuml
left to right direction

rectangle Articles {
(find article) as findArticle
(borrowing article) as borrowArticle
(return article) as returnArticle
(add article) as addArticle
(remove article) as removeArticle
(sort article) as sortArticle
}

rectangle Clients {
(add client) as addClient
(remove client) as removeClient
(find client) as findClient
(sort client) as sortClient
}

client --> borrowArticle
client --> returnArticle
client --> findArticle

employee --> addArticle
employee --> removeArticle
employee --> findArticle
employee --> sortArticle
employee --> addClient
employee --> removeClient
employee --> findClient
employee --> sortClient

@enduml